services:
  caddy:
    build:
      context: .
      args:
        - CADDY_VERSION=${CADDY_VERSION}
    image: caddy
    container_name: caddy
    pull_policy: build
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - caddy_network
    environment:
      - CADDY_DOCKER_CADDYFILE_PATH=/etc/caddy/Caddyfile

networks:
  caddy_network:
    external: true

volumes:
  caddy_data:
    external: true
  caddy_config:
    name: caddy_config
